default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

development:
  <<: *default
  database: booking_api_development

test:
  <<: *default
  database: booking_api_test

production:
  <<: *default
  min_messages: warning
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
